// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4qW1ypVdAeytJXkIqapLcUvtRCjEsP7M',
    appId: '1:410625420632:web:9263eff607329cdb44092d',
    messagingSenderId: '410625420632',
    projectId: 'urban-farming-3efe6',
    authDomain: 'urban-farming-3efe6.firebaseapp.com',
    storageBucket: 'urban-farming-3efe6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_KfsNSne6HsWP0Y3FAGQTPs7LEToiik',
    appId: '1:410625420632:android:a2aca44d78e257b944092d',
    messagingSenderId: '410625420632',
    projectId: 'urban-farming-3efe6',
    storageBucket: 'urban-farming-3efe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtyuUGIDixKqDfHvUm5UVMKO6j7lqSNyg',
    appId: '1:410625420632:ios:d592076db25cbe5c44092d',
    messagingSenderId: '410625420632',
    projectId: 'urban-farming-3efe6',
    storageBucket: 'urban-farming-3efe6.appspot.com',
    iosBundleId: 'com.example.sibolUrbanFarming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtyuUGIDixKqDfHvUm5UVMKO6j7lqSNyg',
    appId: '1:410625420632:ios:c75bfdb6ae6b1dfe44092d',
    messagingSenderId: '410625420632',
    projectId: 'urban-farming-3efe6',
    storageBucket: 'urban-farming-3efe6.appspot.com',
    iosBundleId: 'com.example.sibolUrbanFarming.RunnerTests',
  );
}
